### ISSUE TITLE
Potential bug for multiple hypotheses during inference 

### ISSUE THREAD

**Issue by JunbongJang** [GONGJIA0208/Diffpose#9]
Hi, thank you for the great work!
Your work is helping me with my new project.

I noticed that you simply repeat the "input_uvxyz" by the number of "test_times", but it results in the "output_uvxyz" being the same for each hypothesis. 
I think "input_uvxyz" should be generated from GMM multiple times to get the benefit of multiple hypothesis during inference.
Could you verify it?

Here is the location of potential bug in your code:
https://github.com/GONGJIA0208/Diffpose/blob/af2954513f6f5df274466bf4a45fb84c588b48c6/runners/diffpose_frame.py#L282C13-L284C73

**Comment by GoogQing** [comment]
Good question.

Yeah, we should sample multiple poses from the dataloader via the GMM module instead of simply repeating it multiple times. Although the current one can also benefit the model, we suppose the improvement may be brought by the internal randomness of our diffusion module.

This bug may be caused by the limited time of submitting work to the conference. We will fix that and update our repo in the coming weeks.

**Comment by JunbongJang** [comment]
Thank you for the quick reply!

Ok, that's fine. 
I look forward to more updates.
